# Generated by Django 2.0.3 on 2018-03-14 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myfirstapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
